### ISSUE TITLE
PHL debug to-do list

### ISSUE THREAD

**Issue by buscandoaverroes** [worldbank/gld#61]
- [x] drop all empty variables even if in codebook, do after order
- [x] figure out a unique HHID for years 2017 - ?
- [x] drop unused labels
- [x] ensure in surveys with different employment status per year that `cempst2` -> `newempst`  and `cempst1` -> `empst1`
- [x] #66
- [x] for some years, compare population and labor force participation to official numbers
- [x] add "currently attending" variable for 2004-19. See label script for table object.
- [x] fix multi-round month (april) for 2017, see #52
